image: python:3.8

pages:
  script:
  - pip install --upgrade extruct bs4 requests htmlmin html_sanitizer Pillow html2text
  # Use recent version of ics-py
  - pip install --upgrade git+https://github.com/ics-py/ics-py.git@81b77a2d1e919d87367f97ddafdb1a488a8d2986
  - apt-get update
  - apt-get install minify
  # Run our python script to create our data
  - python schema_to_json.py
  # Compress our javascript
  - mkdir public
  - minify -o public/script.js script.js
  # Compress our css
  - mkdir public/css
  - >
    for file in $(ls css/*); do
      minify -o public/$file $file
    done
  # Copy over our images and our page
  - cp -r images tmp_images index.html eurohpc_events.*.json eurohpc_events.ics project_* public/
  - echo -e "\n\n\e[1mYou can find your build of this repo is available at \n\t\e[32m${CI_PAGES_URL}\e[0m\n\n"
  artifacts:
    paths:
    - public
  only:
  - master
